### ISSUE TITLE
Errors in Wise Chat Renderer

### ISSUE THREAD

**Issue by foxgguy2001** [marcin-lawrowski/wise-chat#59]
When duplicating a pre-configured site as a separate instance in amazon web services, getting the following error:

`[Mon Oct 26 2020 13:46:38 GMT-0700 (Pacific Daylight Time)] [onMaintenanceRequestError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"actions":[],"events":[{"name":"reportAbsentUsers","data":{"users":[]}},{"name":"reportNewUsers","data":{"users":[]}},{"name":"userData","data":{"name":"<REMOVED_USERS_NAME>"}},{"name":"checkSum","data":"f4DYxHHHJgFbf9nvD\/BiV+cD5iANokd1DZFqfGh8RHMYpI65X6AitJVLhqS0IydFd5+igVM4HUjyPUxqPfResEmqSAS7yytDOZuW41deFORL0y+VD\/NGZOKyKqlkC2eipr1SHk2Se9N\/UcG5ixr9pU3ssbNgxx2BHUdzyoqnV+AnouNq8NiaIZ+WWzf2jq3p4N3wA5n\/0QGBg7RIvVcPuHGPxKwtPBq4XOj1Ug1u8YtRndV5KGhSyoHAZSnoqq86"}]}
[Mon Oct 26 2020 13:46:38 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:43 GMT-0700 (Pacific Daylight Time)] [onMessageSentError]
Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145
{"result":"OK"}
[Mon Oct 26 2020 13:46:43 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token < in JSON at position 0
[Mon Oct 26 2020 13:46:44 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:44+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:44 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:47 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:47+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:47 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:50 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:50+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:50 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:53 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:53+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:53 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:56 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:56+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:56 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:58 GMT-0700 (Pacific Daylight Time)] [onMaintenanceRequestError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"actions":[],"events":[{"name":"userData","data":{"name":"<REMOVED_USERS_NAME>"}},{"name":"checkSum","data":"osW3JiF5CeNslywniPUOSryFFXhvkL8fdZmG707iTZgZbzKTTLsVoFxE6fo9lX1F13kBKvVa+aH42TnHNh6oMCHJw3wDr6igbwVCVQhmfqKsEfSHEucBsbiFEfpJl6CJqXp3HLzCY+5QFBhYFG2Fss1QiS5HWMNJ\/5SVE8l8eD3aEFor2GBWeKf2ttvpAL+FwEjHW+eD1aU4aYJ49fy1hugRern8abbu0huTa9yj5A6uZqRVg8088mttw58R8d4P"}]}
[Mon Oct 26 2020 13:46:58 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
[Mon Oct 26 2020 13:46:59 GMT-0700 (Pacific Daylight Time)] [onMessageArrivalError] Notice: Trying to access array offset on value of type int in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wise-chat/src/WiseChatOptions.php on line 145 {"nowTime":"2020-10-26T20:46:59+00:00","result":[{"text":"\n\n
\n\t\n\t\t<REMOVED_USERS_NAME>\n\t<\/span>\n\t<\/span>\n\t
\t\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t\t<\/a>\n\t<\/div>\n\t\n\t\ttest\n\t<\/span>\n<\/div>","id":10}]}
[Mon Oct 26 2020 13:46:59 GMT-0700 (Pacific Daylight Time)] [errorThrown] SyntaxError: Unexpected token N in JSON at position 1
`
Issue is resolved once the plugin is uninstalled and reinstalled

**Comment by marcin-lawrowski** [comment]
Thank you for reporting this. We will be working on fixing it.

**Comment by marcin-lawrowski** [comment]
Fixed in edd2627fb19f6193005e342e561326c30e357aa1
